services:
  games_backend:
    depends_on:
      - db
    environment:
      - MYSQL_CONNECTION_STRING=server=db;database=db;user=user;password=password;
    container_name: games_backend
    image: baerlach/games_backend
    build:
      context: .
      dockerfile: GrpcGreeter/Dockerfile
    ports:
      - "5233:5233"
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - games-db:/var/lib/mysql

volumes:
  games-db:
