CREATE TABLE IF NOT EXISTS Games (
  Id INT AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  ReleaseDate INT NOT NULL,
  PublisherId INT NOT NULL,
  DevStudioId INT NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id),
  FOREIGN KEY(PublisherId) REFERENCES Publisher(Id),
  FOREIGN KEY(DevStudio) REFERENCES DevStudio(Id)
);

CREATE TABLE IF NOT EXISTS GameRatings (
  Id INT AUTO_INCREMENT,
  GameId INT NOT NULL,
  Ip VARCHAR(100) NOT NULL,
  Rating INT NOT NULL CHECK (Rating >= 1 AND Rating <= 5),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id),
  FOREIGN KEY (GameId) REFERENCES Games(Id)
);

CREATE TABLE IF NOT EXISTS Publisher (
  Id INT AUTO_INCREMENT,
  Name VARCHAR(100),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id),
);

CREATE TABLE IF NOT EXISTS DevStudio (
  Id INT AUTO_INCREMENT,
  Name VARCHAR(100),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id),
);

CREATE TABLE IF NOT EXISTS Platform (
  Id INT AUTO_INCREMENT,
  Name VARCHAR(100),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id),
);

CREATE TABLE IF NOT EXISTS Genre (
  Id INT AUTO_INCREMENT,
  Name VARCHAR(100),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id),
);

CREATE TABLE IF NOT EXISTS Game_Platform (
  GameId INT NOT NULL,
  PlatformId INT NOT NULL
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(GameId, PlatformId),
  FOREIGN KEY(GameId) REFERENCES Games(Id),
  FOREIGN KEY(PlatformId) REFERENCES Platform(Id)
);

CREATE TABLE IF NOT EXISTS Game_Genre (
GameId INT NOT NULL,
GenreId INT NOT NULL,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(GameId, GenreId),
FOREIGN KEY(GameId) REFERENCES Games(Id),
FOREIGN KEY(GenreId) REFERENCES Genre(Id)
)