CREATE TABLE IF NOT EXISTS Publisher (
  Id INT AUTO_INCREMENT,
  Name VARCHAR(100),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS Developer (
  Id INT AUTO_INCREMENT,
  Name VARCHAR(100),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id)
);


CREATE TABLE IF NOT EXISTS Game (
  Id INT AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  ReleaseDate INT NOT NULL CHECK (ReleaseDate > 1950),
  PublisherId INT NOT NULL,
    DeveloperId INT NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id),
  FOREIGN KEY(PublisherId) REFERENCES Publisher(Id),
  FOREIGN KEY(DDeveloperId) REFERENCES Developer(Id)
);

CREATE TABLE IF NOT EXISTS GameRating (
  Id INT AUTO_INCREMENT,
  GameId INT NOT NULL,
  Ip VARCHAR(100) NOT NULL,
  Rating INT NOT NULL CHECK (Rating >= 1 AND Rating <= 5),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id),
  FOREIGN KEY (GameId) REFERENCES Game(Id)
);

CREATE TABLE IF NOT EXISTS Platform (
  Id INT AUTO_INCREMENT,
  Name VARCHAR(100),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS Genre (
  Id INT AUTO_INCREMENT,
  Name VARCHAR(100),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS Game_Platform (
  GameId INT NOT NULL,
  PlatformId INT NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(GameId, PlatformId),
  FOREIGN KEY(GameId) REFERENCES Game(Id),
  FOREIGN KEY(PlatformId) REFERENCES Platform(Id)
);

CREATE TABLE IF NOT EXISTS Game_Genre (
GameId INT NOT NULL,
GenreId INT NOT NULL,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(GameId, GenreId),
FOREIGN KEY(GameId) REFERENCES Game(Id),
FOREIGN KEY(GenreId) REFERENCES Genre(Id)
);

INSERT INTO Publisher (Name)
VALUES
  ("Oxymoron"),
  ("Electronic Crafts"),
  ("Macrosoft"),
  ("Activision Sandstrom"),
  ("Give-Two Interactive"),
  ("Ubihard"),
  ("Hundredcent Games"),
  ("Circle Enix"),
  ("Nintendon't");

INSERT INTO Genre (Name)
VALUES
  ("RPG"),
  ("Strategy"), 
  ("RTS"), 
  ("Shooter"),
  ("Beat'em Up"),
  ("Racing"),
  ("Platformer"),
  ("Point'n'Click");

INSERT INTO Platform (Name)
VALUES
  ("PC"),
  ("Playstation"),
  ("Xbox"), 
  ("Switch"), 
  ("Mobile");

INSERT INTO Developer (Name)
VALUES  
  ("Oxymoron"),
  ("Concerned Monkey"),
  ("Pre-Logic"),
  ("Bungee"),
  ("Quartz"),
  ("Gutpunch Studios"),
  ("Sun Studios"),
  ("Magmaboots Studios"),
  ("Alive Human Ship Games"),
  ("ToSoftware Inc."),
  ("StoryWorlds Entertainment"),
  ("Red Bait Studios");